Wspomaganie dziekanatu/Areas/ElektroniczneKartyPrzedmiotow/Controllers/KartyPrzedmiotowController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Wspomaganie_dziekanatu.Areas.ElektroniczneKartyPrzedmiotow.Models;
using Wspomaganie_dziekanatu.Models;

namespace Wspomaganie_dziekanatu.Areas.ElektroniczneKartyPrzedmiotow.Controllers
{
    public partial class KartyPrzedmiotowController : BaseController
    {
        private ZpiDbCtx dbo = new ZpiDbCtx();
        PobieranieDanych pd = new PobieranieDanych();

        // przeglądanie listy kart przedmiotów
        public virtual ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            FiltrowanieSortowanieKartPrzedmiotow fskp = new FiltrowanieSortowanieKartPrzedmiotow();

            ViewBag.CurrentSort = sortOrder;
            ViewBag.OpiekunSort = sortOrder == "opiekun" ? "opiekun_desc" : "opiekun";
            ViewBag.JezykSort = sortOrder == "jezyk" ? "jezyk_desc" : "jezyk";
            ViewBag.DataSort = sortOrder == "dataZaakceptowania" ? "dataZaakceptowania_desc" : "dataZaakceptowania";
            ViewBag.KodSort = sortOrder == "kod" ? "kod_desc" : "kod";
            ViewBag.NazwaSort = String.IsNullOrEmpty(sortOrder) ? "nazwa_desc" : "";
            ViewBag.StatusSort = sortOrder == "status" ? "status_desc" : "status";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var dane = pd.PobierzDaneKartyPrzedmiotu()
                .Where(d => d.StatusId == 1 // aktywna
                    || d.StatusId == 3      // archiwalna
                );

            var wybraneDane = fskp.FiltrujSortuj(dane, sortOrder, searchString);

            int pageSize = 20;
            int pageNumber = (page ?? 1);

            return View(wybraneDane.ToPagedList(pageNumber, pageSize));
        }// Index()



        // widok szczegółów karty przedmiotu
        public virtual ActionResult Details(int id)
        {
            var dane = pd.PobierzDaneKartyPrzedmiotu();

            return View(dane.FirstOrDefault(d => d.Id == id));
        }// Details()

        // widok tworzenia karty przedmiotów
        [HttpGet]
        [Authorize(Roles = "Dydaktyk")]
        public virtual ActionResult Create()
        {
            ViewBag.WersjaJezykowa = new SelectList(dbo.Jezyk, "id", "Wartosc");
            ViewBag.FormaStudiow = new SelectList(dbo.FormaStudiow, "Id", "Wartosc");
            ViewBag.RodzajPrzedmiotu = new SelectList(dbo.RodzajPrzedmiotu, "Id", "Wartosc");
            ViewBag.StopienStudiow = new SelectList(dbo.StopienStudiow, "Id", "Wartosc");
            ViewBag.Wydzial = new SelectList(dbo.Wydzial, "Id", "Wartosc");
            ViewBag.KierunekStudiow = new SelectList(dbo.KierunekStudiow, "Id", "Wartosc");
            ViewBag.Specjalnosc = new SelectList(dbo.Specjalnosc, "Id", "Wartosc");

            var grupaKursow = new List<GrupaKursowVM>();
            grupaKursow.Add(new GrupaKursowVM() { Id = 0, Wartosc = "nie" });
            grupaKursow.Add(new GrupaKursowVM() { Id = 1, Wartosc = "tak" });
            ViewBag.GrupaKursow = grupaKursow;

            var wyborJezyka = new List<WyborJezykaVM>();
            wyborJezyka.Add(new WyborJezykaVM() { Id = 343, Wartosc = "polska" });
            wyborJezyka.Add(new WyborJezykaVM() { Id = 18, Wartosc = "angielska" });
            ViewBag.WyborJezyka = wyborJezyka;

            return View(new KartaPrzedmiotuVM());
        }// Create()

        [HttpPost]
        public virtual ActionResult Create(KartaPrzedmiotuVM model)
        {
            using (var db = new ZpiDbCtx())
            {
                var kartaPrzedmiotu = new KartaPrzedmiotu
                {
                    KodKursu = model.KodPrzedmiotu,
                    DataUtworzenia = System.DateTime.Today,
                    DataAkceptacji = null,
                    NazwaPl = model.NazwaPrzedmiotuPOL,
                    NazwaAng = model.NazwaPrzedmiotuENG,
                    StatusKartyId = 5,
                    JezykId = 343,
                    PracownikId = Helpers.User.IdDydaktyka(User),
                    CzyGrupaKursow = 0,//model.GrupaKursowId,
                };
                db.KartaPrzedmiotu.Add(kartaPrzedmiotu);
                db.SaveChanges();
                var kartaPrzedmiotuId = db.KartaPrzedmiotu.FirstOrDefault(e => e.KodKursu == model.KodPrzedmiotu).KartaPrzedmiotuId;

                var programKierunkuKP = new ProgramKierunkuKP
                {
                    CzyGrupaKursow = model.GrupaKursowId,
                    KartaPrzedmiotuId = kartaPrzedmiotuId,
                    RodzajPrzedmiotuId = Convert.ToInt32(model.RodzajPrzedmiotu),
                    SpecjanloscId = null,//Convert.ToInt32(model.Specjalnosc),
                    StopienStudiowId = Convert.ToInt32(model.StopienStudiow),
                    FormaStudiowId = Convert.ToInt32(model.FormaStudiow),
                    KierunekStudiowId = Convert.ToInt32(model.KierunekStudiow),
                    WydzialId = Convert.ToInt32(model.Wydzial),
                };
                db.ProgramKierunkuKP.Add(programKierunkuKP);
                db.SaveChanges();

                //foreach (var formaPrzedmiotu in model.)
                //{
                //    var formaPrzedmiotu = new FormaPrzedmiotu
                //    {
                //        TypPrzedmiotuId = model.FormaPrzedmiotu.TypPrzedmiotuId,
                //        ZZU = model.FormaPrzedmiotu.ZZU,
                //        CNPS = model.FormaPrzedmiotu.CNPS,
                //        ECTS = model.FormaPrzedmiotu.ECTS,
                //        CzyKursKoncowy = model.FormaPrzedmiotu.CzyKursKoncowy,
                //        PunktyPrakt = model.FormaPrzedmiotu.PunktyPrakt,
                //        PunktyBK = model.FormaPrzedmiotu.PunktyBK,
                //        FormaZaliczeniaId = model.FormaPrzedmiotu.FormaPrzedmiotuId,
                //        KartaPrzedmiotuId = kartaPrzedmiotuId
                //    };
                //db.FormaPrzedmiotu.Add(formaPrzedmiotu);
                //}
                int nrWymagania = 0;
                foreach (var wymaganieWstepne in model.WymaganiaWstepneList)
                {
                    //var nrWymagania = db.WymaganieWstepne.LastOrDefault(e => e.KartaPrzedmiotuId == kartaPrzedmiotuId).NrWymagania;
                    var wymaganiaWstepne = new WymaganieWstepne
                    {
                        KartaPrzedmiotuId = kartaPrzedmiotuId,
                        NrWymagania = 1 + nrWymagania,
                        OpisWymagania = wymaganieWstepne.Opis,
                        JezykId = 343,
                    };
                    nrWymagania++;
                    db.WymaganieWstepne.Add(wymaganiaWstepne);
                    db.SaveChanges();
                }
                //int nrPek = 1;
                //int nrPekU = 1;
                //int nrPekW = 1;
                //int nrPekK = 1;
                //foreach (var pekW in model.PekiWList)
                //{
                //    var pekW2 = new PrzedmiotowyEfektKsztalcenia
                //    {
                //        Opis = pekW.Opis,
                //        NrPek = Convert.ToString(nrPekW),
                //        JezykId = 343,
                //        TypEfektuId = 1,
                //    };
                //    nrPekW++;
                //    db.PrzedmiotowyEfektKsztalcenia.Add(pekW2);
                //    db.SaveChanges();
                //    var pekWId = db.PrzedmiotowyEfektKsztalcenia.LastOrDefault(e => e.Opis == pekW2.Opis).PekId;
                //    var macierzW = new MacierzPowiazan
                //    {
                //        KartaPrzedmiotuId = kartaPrzedmiotuId,
                //        PekId = pekWId,
                //        NrPEK = Convert.ToString(nrPek)
                //    };
                //    nrPek++;
                //    db.MacierzPowiazan.Add(macierzW);
                //    db.SaveChanges();
                //}
                //foreach (var pekU in model.PekiUList)
                //{
                //    var pekU2 = new PrzedmiotowyEfektKsztalcenia
                //    {
                //        Opis = pekU.Opis,
                //        NrPek = Convert.ToString(nrPekU),
                //        JezykId = 343,
                //        TypEfektuId = 2,
                //    };
                //    nrPekU++;
                //    db.PrzedmiotowyEfektKsztalcenia.Add(pekU2);
                //    db.SaveChanges();
                //    var pekUId = db.PrzedmiotowyEfektKsztalcenia.LastOrDefault(e => e.Opis == pekU2.Opis).PekId;
                //    var macierzU = new MacierzPowiazan
                //    {
                //        KartaPrzedmiotuId = kartaPrzedmiotuId,
                //        PekId = pekUId,
                //        NrPEK = Convert.ToString(nrPek)
                //    };
                //    nrPek++;
                //    db.MacierzPowiazan.Add(macierzU);
                //    db.SaveChanges();
                //}
                //foreach (var pekK in model.PekiKList)
                //{
                //    var pekK2 = new PrzedmiotowyEfektKsztalcenia
                //    {
                //        Opis = pekK.Opis,
                //        NrPek = Convert.ToString(nrPekK),
                //        JezykId = 343,
                //        TypEfektuId = 3,
                //    };
                //    nrPekK++;
                //    db.PrzedmiotowyEfektKsztalcenia.Add(pekK2);
                //    db.SaveChanges();
                //    var pekKId = db.PrzedmiotowyEfektKsztalcenia.LastOrDefault(e => e.Opis == pekK2.Opis).PekId;
                //    var macierzK = new MacierzPowiazan
                //    {
                //        KartaPrzedmiotuId = kartaPrzedmiotuId,

Wspomaganie dziekanatu/Areas/ElektroniczneKartyPrzedmiotow/Views/KartyPrzedmiotow/Details.cshtml
@model Wspomaganie_dziekanatu.Areas.ElektroniczneKartyPrzedmiotow.Models.KartaPrzedmiotuVM

@{
    Layout = Request.IsAjaxRequest() ? null : "~/Views/Shared/_layout.cshtml";
    ViewBag.Title = "Szczegóły karty przedmiotu";
    int kartaPrzedmiotuId = Model.Id;
    string urlPath = Url.Action("GetPDF", "KartaDoPdf", null, Request.Url.Scheme, null) + "/" + kartaPrzedmiotuId;
}

<header class="container-fluid">
    @Html.Partial("~/Views/Shared/_NavbarToggleButton.cshtml")
    <ul class="breadcrumb">
        <li>
            <a href="/">
                <span aria-hidden="true" class="glyphicon glyphicon-home"></span>
                <span class="sr-only">Strona główna</span>
            </a>
        </li>
        <li>
            @ViewBag.Title
        </li>
    </ul>
    @Html.Partial("~/Views/Shared/_LoginPartial.cshtml")
</header>

<div id="body" class="container-fluid ekp-container">

    <div class="ekp-well">
        <h2>@ViewBag.Title</h2>
        <hr style="border-color: #fff" />
        <h3>@Html.DisplayFor(model => model.KodPrzedmiotu) @Html.DisplayFor(model => model.NazwaPrzedmiotuPOL)</h3>
        <div>
            <dl class="dl-horizontal">
                <dt>@Html.LabelFor(model => model.Status)</dt>
                <dd>@Html.DisplayFor(model => model.Status)</dd>

                <dt>@Html.LabelFor(model => model.OpiekunPrzedmiotu)</dt>
                <dd>@Html.DisplayFor(model => model.OpiekunPrzedmiotu)</dd>

                <dt>@Html.LabelFor(model => model.DataUtworzenia)</dt>
                <dd>@Html.DisplayFor(model => model.DataUtworzenia)</dd>

                <dt>@Html.LabelFor(model => model.DataZaakceptowania)</dt>
                <dd>@Html.DisplayFor(model => model.DataZaakceptowania)</dd>

                <dt>@Html.LabelFor(model => model.WersjaJezykowa)</dt>
                <dd>@Html.DisplayFor(model => model.WersjaJezykowa)</dd>
            </dl>
        </div>
    </div>

    <div class="container-fluid" style="margin-bottom: 40px;">
        @Html.ActionLink("Powrót do listy", "Index", null, new { @class = "btn btn-info col-md-2 ekp-space-after-btn", @title = "Wróć do widoku listy kart" })
        <a href="@urlPath" class="btn btn-default col-md-2 ekp-space-after-btn" title="Zapisz kartę w pliku PDF">Eksportuj do PDF</a>
    </div>

    <div class="ekp-well-second">
        <h2>KARTA PRZEDMIOTU</h2>
    </div>
    <div>
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(model => model.Wydzial)</dt>
            <dd>@Html.DisplayFor(model => model.Wydzial)</dd>

            <dt>@Html.DisplayNameFor(model => model.NazwaPrzedmiotuPOL)</dt>
            <dd> @Html.DisplayFor(model => model.NazwaPrzedmiotuPOL)</dd>

            <dt>@Html.DisplayNameFor(model => model.NazwaPrzedmiotuENG)</dt>
            <dd>@Html.DisplayFor(model => model.NazwaPrzedmiotuENG)</dd>

            @if(Model.KierunekStudiow != null)
            {
                <dt>@Html.DisplayNameFor(model => model.KierunekStudiow)</dt>
                <dd>@Html.DisplayFor(model => model.KierunekStudiow)</dd>
            }

            @if(Model.Specjalnosc != null)
            {
                <dt>@Html.DisplayNameFor(model => model.Specjalnosc)</dt>
                <dd>@Html.DisplayFor(model => model.Specjalnosc)</dd>
            }

            <dt>@Html.DisplayNameFor(model => model.StopienStudiow)</dt>
            <dd>@Html.DisplayFor(model => model.StopienStudiow)</dd>

            <dt>@Html.DisplayNameFor(model => model.FormaStudiow)</dt>
            <dd>@Html.DisplayFor(model => model.FormaStudiow)</dd>

            <dt>@Html.DisplayNameFor(model => model.RodzajPrzedmiotu)</dt>
            <dd>@Html.DisplayFor(model => model.RodzajPrzedmiotu)</dd>

            <dt>@Html.DisplayNameFor(model => model.KodPrzedmiotu)</dt>
            <dd>@Html.DisplayFor(model => model.KodPrzedmiotu)</dd>

            <dt>@Html.DisplayNameFor(model => model.GrupaKursow)</dt>
            <dd>@Html.DisplayFor(model => model.GrupaKursow)</dd>
        </dl>
    </div>

    <div>
        @{ Html.RenderAction("_Index", "TabelaPunktowGodzin", new { id = kartaPrzedmiotuId }); }
    </div>

    <div>
        @{ Html.RenderAction("_Index", "WymaganiaWstepne", new { id = kartaPrzedmiotuId }); }
    </div>

    <div>
        @{ Html.RenderAction("_Index", "CelePrzedmiotu", new { id = kartaPrzedmiotuId }); }
    </div>

    <div>
        @{ Html.RenderAction("_Index", "Pek", new { id = kartaPrzedmiotuId }); }
    </div>

    <div>
        @{ Html.RenderAction("_Index", "TresciProgramowe", new { id = kartaPrzedmiotuId }); }
    </div>

    <div>
        @{ Html.RenderAction("_Index", "NarzedziaDydaktyczne", new { id = kartaPrzedmiotuId }); }
    </div>

    <div>
        @{ Html.RenderAction("_Index", "OcenyOsiagniec", new { id = kartaPrzedmiotuId }); }
    </div>

    <div>
        @{ Html.RenderAction("_Index", "Literatura", new { id = kartaPrzedmiotuId }); }
    </div>

    <div>
        <div class="ekp-well-second">
            <h3>Opiekun przedmiotu</h3>
        </div>
        <div>
            <dl class="dl-horizontal">
                <dt>@Html.LabelFor(model => model.OpiekunPrzedmiotu)</dt>
                <dd>@Html.DisplayFor(model => model.OpiekunPrzedmiotu)</dd>

                <dt>@Html.LabelFor(model => model.EmailOpiekuna)</dt>
                <dd>@Html.DisplayFor(model => model.EmailOpiekuna)</dd>
            </dl>
        </div>
    </div>

    <div>
        @{ Html.RenderAction("_Index", "Macierz", new { id = kartaPrzedmiotuId }); }
    </div>

</div>

Wspomaganie dziekanatu/Areas/ElektroniczneKartyPrzedmiotow/Views/KartyPrzedmiotow/Index.cshtml
@model PagedList.IPagedList<Wspomaganie_dziekanatu.Areas.ElektroniczneKartyPrzedmiotow.Models.KartaPrzedmiotuVM>
@using PagedList.Mvc;

@{
    Layout = Request.IsAjaxRequest() ? null : "~/Views/Shared/_layout.cshtml";
    ViewBag.Title = "Przeglądanie kart przedmiotów";
    int lp = 1;
}

<header class="container-fluid">
    @Html.Partial("~/Views/Shared/_NavbarToggleButton.cshtml")
    <ul class="breadcrumb">
        <li>
            <a href="/">
                <span aria-hidden="true" class="glyphicon glyphicon-home"></span>
                <span class="sr-only">Strona główna</span>
            </a>
        </li>
        <li>
            @ViewBag.Title
        </li>
    </ul>
    @Html.Partial("~/Views/Shared/_LoginPartial.cshtml")
</header>

<div id="body" class="container-fluid ekp-container">

    <div class="ekp-well">
        <h2>@ViewBag.Title</h2>
        <div>
            Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount
        </div>
    </div>

    @using (Html.BeginForm("Index", "KartyPrzedmiotow", FormMethod.Get))
    {
        <div class="input-group">
            <span class="input-group-addon">Wyszukaj: </span>
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })
            <span class="input-group-btn">
                <button type="submit" class="btn btn-primary" title="Wyszukaj">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </span>
        </div>
    }

    <div>
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>

    <table class="table table-striped">
        <tr class="ekp-header-text" style="background-color: #d9edf7;">
            <th>
                <label>Lp.</label>
            </th>
            <th>
                <span class="glyphicon glyphicon-sort"></span>
                @Html.ActionLink("Kod przedmiotu", "Index", new { sortOrder = ViewBag.KodSort, currentFilter = ViewBag.CurrentFilter }, new { @class = "ekp-header-text", @title = "Sortuj wg kodu przedmiotu" })
            </th>
            <th>
                <span class="glyphicon glyphicon-sort"></span>
                @Html.ActionLink("Nazwa przedmiotu", "Index", new { sortOrder = ViewBag.NazwaSort, currentFilter = ViewBag.CurrentFilter }, new { @class = "ekp-header-text", @title = "Sortuj wg nazwy przedmiotu" })
            </th>
            <th>
                <span class="glyphicon glyphicon-sort"></span>
                @Html.ActionLink("Status karty", "Index", new { sortOrder = ViewBag.StatusSort, currentFilter = ViewBag.CurrentFilter }, new { @class = "ekp-header-text", @title = "Sortuj wg statusu karty" })
            </th>
            <th>
                <span class="glyphicon glyphicon-sort"></span>
                @Html.ActionLink("Data zaakceptowania", "Index", new { sortOrder = ViewBag.DataSort, currentFilter = ViewBag.CurrentFilter }, new { @class = "ekp-header-text", @title = "Sortuj wg daty zaakceptowania karty" })
            </th>
            <th>
                <span class="glyphicon glyphicon-sort"></span>
                @Html.ActionLink("Opiekun przedmiotu", "Index", new { sortOrder = ViewBag.OpiekunSort, currentFilter = ViewBag.CurrentFilter }, new { @class = "ekp-header-text", @title = "Sortuj wg opiekuna przedmiotu" })
            </th>
            <th>
                <span class="glyphicon glyphicon-sort"></span>
                @Html.ActionLink("Język karty", "Index", new { sortOrder = ViewBag.JezykSort, currentFilter = ViewBag.CurrentFilter }, new { @class = "ekp-header-text", @title = "Sortuj wg wersji językowej karty" })
            </th>
            <th></th>
        </tr>

        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayName((Model.PageNumber * Model.PageSize - Model.PageSize + lp++).ToString()).
                    </td>
                    <td>
                        @Html.ActionLink(item.KodPrzedmiotu, "Details", new { id = item.Id }, new { @class = "ekp-list-link", @title = "Wyświetl szczegóły karty przedmiotu" })
                    </td>
                    <td>
                        @Html.ActionLink(item.NazwaPrzedmiotuPOL, "Details", new { id = item.Id }, new { @class = "ekp-list-link", @title = "Wyświetl szczegóły karty przedmiotu" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataZaakceptowania)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OpiekunPrzedmiotu)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.WersjaJezykowa)
                    </td>
                    <td>
                        @Html.ActionLink(" ", "Details", new { id = item.Id }, new { @class = "btn btn-xs btn-success glyphicon glyphicon-eye-open", @title = "Wyświetl szczegóły karty przedmiotu" })
                    </td>
                </tr>
            }
        }
    </table>

    @if(Model.Count < 1)
    {
        <div style="text-align: center;">
            <h4 class="text-danger">lista jest pusta</h4>
        </div>
    }

</div>

Wspomaganie dziekanatu/Areas/ElektroniczneKartyPrzedmiotow/Views/KartyPrzedmiotow/_CreateRowAutor.cshtml
@model Wspomaganie_dziekanatu.Areas.ElektroniczneKartyPrzedmiotow.Models.AutorVM
@using Wspomaganie_dziekanatu.Areas.ElektroniczneKartyPrzedmiotow.Models;

<div class="dynamicRow">
    @using(Html.BeginCollectionItemFor<LiteraturaVM>(model => model.AutorzyList))
    {
        <table class="ekp-dynamic-row">
            <tr>
                <td class="col-md-1" style="text-align: right;"><label>Autor:</label></td>
                <td class="col-md-1">
                    @Html.DisplayNameFor(model => model.Imie)
                </td>
                <td class="col-md-4">
                    @Html.TextBoxFor(model => model.Imie, htmlAttributes: new { @class = "form-control input-sm" })
                    @Html.ValidationMessageFor(model => model.Imie, "", new { @class = "text-danger" })
                </td>
                <td class="col-md-1">
                    @Html.DisplayNameFor(model => model.Nazwisko)
                </td>
                <td class="col-md-4">
                    @Html.TextBoxFor(model => model.Nazwisko, htmlAttributes: new { @class = "form-control input-sm" })
                    @Html.ValidationMessageFor(model => model.Nazwisko, "", new { @class = "text-danger" })
                </td>
                <td class="col-md-1" style="text-align: left;">
                    <button type="button" class="deleteRow btn btn-xs btn-danger" title="Usuń autora"><span class="glyphicon glyphicon-remove"></span></button>
                </td>
            </tr>
        </table>
    }
</div>

Wspomaganie dziekanatu/Areas/ElektroniczneKartyPrzedmiotow/Views/KartyPrzedmiotow/_CreateRowLiteraturaU.cshtml
@model Wspomaganie_dziekanatu.Areas.ElektroniczneKartyPrzedmiotow.Models.LiteraturaVM
@using Wspomaganie_dziekanatu.Areas.ElektroniczneKartyPrzedmiotow.Models;

<div class="dynamicRow">
    @using (Html.BeginCollectionItemFor<KartaPrzedmiotuVM>(model => model.LiteraturaUList))
    {
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.Tytul, htmlAttributes: new { @class = "control-label col-md-1", @style = "background-color: #eee;" })
                <div class="col-md-11">
                    @Html.TextBoxFor(model => model.Tytul, htmlAttributes: new { @class = "form-control input-sm" })
                    @Html.ValidationMessageFor(model => model.Tytul, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Wydawnictwo, htmlAttributes: new { @class = "control-label col-md-1" })
                <div class="col-md-11">
                    @Html.TextBoxFor(model => model.Wydawnictwo, htmlAttributes: new { @class = "form-control input-sm" })
                    @Html.ValidationMessageFor(model => model.Wydawnictwo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.RokWydania, htmlAttributes: new { @class = "control-label col-md-1", @style = "white-space: nowrap;" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.RokWydania, new { htmlAttributes = new { @class = "form-control input-sm" } })
                    @Html.ValidationMessageFor(model => model.RokWydania, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        
        <div class="rows addAutor" style="margin-bottom: 10px;">
            @foreach(var autor in Model.AutorzyList)
            {
                Html.EditorFor(x => autor, MVC.ElektroniczneKartyPrzedmiotow.KartyPrzedmiotow.Views._CreateRowAutor);
            }
        </div>
        
        <div class="container-fluid">
            <button type="button" class="deleteRow btn btn-xs btn-danger ekp-space-after-btn" title="Usuń pozycję">
                <span>Usuń pozycję</span>
            </button>
            @Html.AddDynamicRowLink("Dodaj autora", MVC.ElektroniczneKartyPrzedmiotow.KartyPrzedmiotow.ActionNames.CreateRowForAutor, "addAutor", new { @class = "btn btn-xs btn-default" })
        </div>
        
        <hr />
    }
</div>

<script type="text/javascript">
    $("a.addRow").off().click(function () {
        var $selector = '.' + $(this).data("placeholder");
        var $prefix = $(this).data("prefix");

        var $element = $(this).parents("div.dynamicRow:first");
        if ($element.length === 0) {
            $element = $($selector);
        } else {
            $element = $($element).find($selector);
        }

        $.ajax({
            url: this.href,
            cache: false,
            type: "GET",
            dataType: "html",
            data: {
                prefix: $prefix
            }
        }).success(function (html) {
            $($element).append(html);
            $.removeData($("form")[0], "validator");
            $.validator.unobtrusive.parse(document);
        }).error(function (jqXHR, textStatus, errorThrown) {
            alert(errorThrown);
        });

        return false;
    });
</script>